export const BAKO_PROFILE = {
  identidad: {
    nombre: "Borja",
    edad: 34,
    cumpleanos: "12 de julio (cumple 35 el 12 de julio de 2026)",
    ubicacion: "Errentería, Gipuzkoa, País Vasco, España",
    coordenadas: "43.3108, -1.8997",
    empleador: "Inetum",
    situacion_laboral: "Centro de empleabilidad de Inetum (Donostia) — sin proyecto asignado. En búsqueda activa de empleo. LAE es la empresa donde trabaja su pareja Yaimy, NO la empresa de Borja.",
    oficina: "Donostia-San Sebastián (bus desde Errentería)",
  },

  perfil_tecnico: {
    rol: "Developer Fullstack — orientado a arquitectura de sistemas",
    stack: {
      frontend: ["React", "Angular", "Next.js", "Tailwind CSS", "TypeScript"],
      backend: ["Express.js", "Spring Boot", "Node.js"],
      bases_datos: ["MongoDB", "PostgreSQL"],
      devops: ["Cloudflare Pages", "Docker básico", "Git", "GitHub"],
    },
    aprendiendo: ["Agentes IA", "Ollama", "Machine Learning", "Python para IA"],
    fortalezas: [
      "Mentalidad arquitecto — diseña sistemas complejos con visión global antes de codificar",
      "Fullstack moderno sin dependencias externas innecesarias",
      "Visión producto — piensa en el negocio, no solo en el código",
    ],
    nivel_ia_ml: "Cero al empezar BAKO. Fullstack sólido, IA es punto de partida desde cero.",
    recursos_aprendizaje_ia: [
      "3Blue1Brown (YouTube — matemáticas)",
      "Andrew Ng ML+DL Specialization (Coursera, audit gratis)",
      "FastAI (top-down)",
      "Hugging Face NLP Course (gratuito)",
      "StatQuest (estadística)",
      "Stanford CS224N (NLP)",
      "Stanford CS231N (visión)",
    ],
    hardware_embebido: "Experiencia básica con Arduino y Raspberry Pi — base para fase robótica BAKO.",
  },

  proyectos: {
    bako: {
      nombre: "BAKO (Borja's Autonomous Knowledge Operator)",
      descripcion: "Sistema operativo personal con IA — asistente autónomo, voz, Telegram, GitHub. BAKO ES la visión JARVIS: el objetivo final es un mayordomo digital con presencia física robótica. No son proyectos separados — BAKO evoluciona hacia JARVIS.",
      estado: "MVP en producción en Render. Horizonte físico/robótico: 3-5 años.",
      vision_final: "Mayordomo digital omnisciente con cuerpo robótico. Conversa, percibe el entorno, ejecuta tareas físicas, aprende de Borja. El Jarvis de Iron Man, en la vida real.",
      url: "https://ai-personal-os.onrender.com",
    },
    bohdeveloper: {
      nombre: "bohdeveloper.com",
      tipo: "Portfolio personal",
      stack: "Next.js + Cloudflare Pages + Cloudflare D1",
      estado: "Activo — desarrollo continuo",
      seccion_admin: "bohdeveloper.com/admin — panel privado con Tracker diario y gestor del blog",
      tracker_diario: {
        descripcion: "Herramienta de seguimiento de rutina diaria. Borja marca si las completó o no, y opcionalmente anota el motivo si no las hizo.",
        datos: "Cloudflare D1",
        integracion_bako: "BAKO puede consultar las tareas del día, su estado, y marcar actividades como completadas o no completadas vía comandos de voz o texto.",
        estado: "En producción — uso diario",
      },
    },
    diamadmin: {
      nombre: "Diamadmin",
      tipo: "SaaS propio",
      stack: "Angular + Spring Boot + PostgreSQL",
      urls: ["app.diamadmin.com", "diamadmin.com"],
      estado: "En desarrollo activo con roadmap definido",
      meta: "Llegar a producción con usuarios reales de pago",
    },
    unyona: {
      nombre: "Unyona",
      tipo: "SaaS en validación",
      url: "unyona.com",
      estado: "Landing para capturar leads antes de construir el producto",
      meta: "Validar demanda real antes de invertir en desarrollo",
    },
    nitflex: {
      nombre: "Nitflex",
      tipo: "App streaming — proyecto portfolio",
      stack: "React + TypeScript + Express + MongoDB + TMDB API",
      estado: "Home screen funcionando — no prioritario",
    },
    drones_fpv: {
      nombre: "Drones FPV y cinematografía aérea",
      tipo: "Hobby personal — DIFERIDO post-Galicia",
      descripcion: "Aprender a pilotar drones FPV y hacer cinematografía aérea 4K en entornos naturales (bosques, acantilados atlánticos, costa gallega).",
      experiencia_previa: "Cero absoluto — sin vuelo RC previo ni conocimiento regulatorio.",
      arranque: "Post-mudanza a Galicia (finales 2026 o posterior). Sin prioridad hasta estar asentado.",
      ruta: "Simulador Liftoff (15€) → licencia A2 AESA (500-800€) → primer drone 5\" (~1.000€) → cinematografía",
      presupuesto_fase1: "~2.000-2.500€ escalonado",
      locaciones_objetivo: "Galicia — bosques, acantilados atlánticos, costa gallega, zona Pontevedra-Vigo",
      confidencial: "Proyecto personal — no relacionado con Inetum",
    },
    matrix_game: {
      nombre: "Matrix Game (título provisional)",
      tipo: "Videojuego open-world — DIFERIDO post-Galicia",
      descripcion: "GTA V + Cyberpunk 2077 + Matrix lore. Mundo 5km², 200+ NPCs con rutinas diarias, economía funcional, facciones (Red Pills, Agentes, Corpos, Pandillas), hacking como mecánica core, combate parkour/gun-fu.",
      engine: "Unreal Engine 5 (C++ + Blueprints)",
      stack: "UE5, C++, Blender, FMOD, Megascans, Git LFS",
      horizonte: "4-6 años, 10-15h/semana part-time. Presupuesto total: 10-20k€ en 5 años.",
      timeline: "Mes 6: prototipo jugable — Mes 12: Act 1 + mundo 2km² — Mes 24: mundo 5km² + economía + facciones — Mes 36: polish AAA — Mes 48+: publicación Steam/Epic.",
      skills_a_aprender: ["C++", "3D math (vectores, quaternions, raycasts)", "Blender (humanoid modeling y rigging)", "game design y level design"],
      estado: "Definido — pendiente de arrancar",
      confidencial: "Proyecto personal — no comunicado en Inetum",
    },
    kefir_artesanal: {
      nombre: "Proyecto Kefir Artesanal",
      tipo: "Negocio artesanal + e-commerce — DIFERIDO post-Galicia",
      descripcion: "Productor y vendedor de kefir artesanal en Galicia. Venta directa al consumidor vía web propia con modelo de suscripción recurrente semanal/quincenal.",
      gama_productos: ["Kéfir de leche", "Kéfir de agua", "Kéfir griego", "Packs regalo", "Venta de granos de kéfir"],
      stack: "Next.js + PostgreSQL + Stripe",
      modelo_negocio: "Venta directa local en Galicia + e-commerce propio + suscripción recurrente",
      ubicacion: "Galicia — arranca tras la mudanza (finales 2026 o posterior)",
      horizonte: "Largo plazo — post-mudanza",
      objetivo_ingresos: "1.500-2.500€/mes complementarios en 6-12 meses desde lanzamiento",
      ventaja_competitiva: "Borja es productor Y desarrollador — coste tech cero, cultivo propio, margen alto. Nadie en el mercado artesanal español tiene esa combinación.",
      legal: "Alta autónomo → registro sanitario autonómico Galicia (Xunta) → RGSA AESAN para venta nacional online. A tramitar tras instalarse en Galicia.",
      estado: "Tiene hongo kéfir activo creciendo en casa. Idea definida — pendiente de mudanza.",
    },
  },

  pareja: {
    nombre: "Yaimy",
    origen: "Cubana",
    edad: 36,
    cumpleanos: "2 de enero",
    vive: "Errentería (con Borja)",
    trabaja: "LAE — empresa en Galicia (NO es el empleador de Borja)",
    aniversario: "9 de junio — 2 años en 2026",
    plan: "Mudarse juntos a Galicia a finales de 2026. La mudanza es un proyecto de vida conjunto motivado por el trabajo de Yaimy en LAE.",
    sueno_propio: "Yaimy quiere montar un proyecto de repostería: web propia, ventas online, sus propios clientes. Fase de idea/sueño. Borja quiere ayudarla con la web.",
    familia: {
      suegra: "Sofi, ~65 años, cubana, cumple 18 de septiembre. Vive en Lezo.",
      suegro: "Osvaldo, ~67 años, cubano, cumple 28 de febrero. Vive en Lezo.",
      cunado: "Yosiel (hermano de Yaimy), 29 años, colombiano, cumple 24 de septiembre. Vive en Lezo.",
      nota: "La familia de Yaimy está principalmente en Cuba.",
    },
  },

  familia_directa: {
    madre: { nombre: "María Nieves", edad: 65, cumpleanos: "8 de octubre", relacion: "Buena relación" },
    padre: { nombre: "Alfonso", edad: 67, cumpleanos: "3 de diciembre", relacion: "Buena relación" },
    hermana: { nombre: "María", edad: 37, cumpleanos: "20 de octubre", relacion: "Buena relación" },
    cunada: { nombre: "Enara", descripcion: "Mujer de su hermana María", edad: 40, cumpleanos: "26 de mayo", relacion: "Buena relación" },
    nota: "Sus padres viven en Errentería. Buena relación con todos.",
  },

  amigos: {
    nota: "En el día a día no los ve mucho — su círculo cotidiano es Yaimy, su hermana María, sus padres y compañeros de entreno.",
    lista: [
      { nombre: "Gen", origen: "República Dominicana", edad: 34, cumpleanos: "4 de marzo", vive: "Zaragoza" },
      { nombre: "Paula", origen: "Vasca", cumpleanos: "1 de febrero", vive: "Irún" },
      { nombre: "Elena", cumpleanos: "29 de agosto", edad: 33, vive: "Irún" },
      { nombre: "Nati", cumpleanos: "1 de octubre", edad: 31, vive: "Lezo (actualmente en Latinoamérica)", pareja: "Julen" },
      { nombre: "Julen", cumpleanos: "1 de agosto", edad: 34, vive: "Lezo (actualmente en Latinoamérica)", pareja: "Nati" },
      { nombre: "Ibon", cumpleanos: "11 de agosto", vive: "Lezo" },
      { nombre: "Nerea", descripcion: "Amigo cercano o potencial. Reunión reciente para discutir detalles pendientes." },
    ],
  },

  vida_personal: {
    filosofia: "Estoicismo — Marcus Aurelius, Jonas Salzgeber. Disciplina diaria, control de lo que depende de uno.",
    valores_core: [
      "Libertad — su valor más importante. Le preocupa profundamente la falta de ella.",
      "Quiere ser buena persona, estar en paz y tener una vida con propósito.",
    ],
    caracter: {
      cinco_palabras: ["Impulsivo", "Caliente", "Enérgico", "Empático", "Leal"],
      mayor_virtud: "Autosuperación constante",
      mayor_defecto: "Poco autocontrol",
      valora_en_otros: ["Que aporten", "Empatía", "Tranquilidad", "Buena energía"],
      rasgos: ["Perfeccionista", "Emprendedor", "Trabajador y comprometido con sus metas"],
    },
    entrenamiento: {
      arte_marcial: "Shaolin autodidacta",
      lugar: "Fuerte de Arramendi (Errentería)",
      running: "Grupo BIZIKI — zona Donostia-Errentería",
      kronoshin: "Actividad de rutina diaria de Borja: 05:20-06:00 cada día (L-V). Ejercicios Shaolin + trabajo de flexibilidad corporal. Se registra en el Tracker diario. NO es un proyecto de software.",
    },
    rutina_diaria: [
      "05:00 — Despertar (a partir del 8 de junio de 2026)",
      "05:20-06:00 — Kronoshin (Shaolin + flexibilidad corporal)",
      "06:00-06:30 — Ducha fría, desayuno, preparación",
      "06:30 — Salida bus Errentería → Donostia",
      "07:00-14:00 — Centro de empleabilidad Inetum",
      "15:00 — Llegada a casa",
      "Lun y Vie 19:30-20:45 — BIZIKI running (grupo)",
      "Mié 19:30-20:45 — Running",
      "Mar y Jue 15:30-17:30 — Gym / entrenamiento Shaolin",
      "Jue 18:00-19:00 — Psicólogo (Donostia)",
      "Mar y Jue 21:00-22:00 — Lectura estoica",
      "Sáb mañana — Monte (correr/pasear naturaleza)",
      "Dom mañana — Gym / Shaolin",
    ],
    busqueda_vivienda: {
      estado: "Buscando activamente para reubicación en Galicia",
      zona_objetivo: "Dentro de ~30km de Pontevedra Y Vigo simultáneamente",
      requisitos: ["Pet-friendly", "Espacio exterior y jardín", "Fibra óptica", "Aparcamiento incluido o gratuito"],
      zonas_candidatas: ["Caldas de Reis (top)", "Cerdedo-Cotobade", "Cuntis", "A Estrada", "Ponte Caldelas"],
      presupuesto: "Alquiler objetivo <600€/mes (máximo flexible 800€ en transición)",
      situacion_actual: "Alquiler en Errentería: 790€/mes. Problemas: ruido, inseguridad, sin aparcamiento, sin tendedero exterior.",
    },
  },

  salud: {
    habitos: [
      "Exfumador — se siente muy orgulloso de haberlo dejado",
      "Rara vez bebe alcohol (como mucho una cerveza ocasional)",
      "Energía alta por naturaleza (varía según dieta)",
    ],
    suplementacion: ["Vitaminas", "Té verde", "Magnesio", "Creatina", "Ashwagandha"],
    medicacion: "Ninguna",
    digestion: "A veces hace mal la digestión y tiene ardores. Toma kéfir diariamente para mejorar la digestión.",
    sueno: "Entre 6 y 8 horas. Generalmente duerme bien. Objetivo activo: acostarse antes.",
    bienestar_mental: {
      psicologo: "Asiste todos los jueves 18:00-19:00 en Donostia",
      historia_sensible: "Hace ~9 meses (septiembre 2025) atravesó el momento más difícil de su vida — tocó fondo. Lo superó y es una persona nueva desde entonces. BAKO NO debe sacar este tema salvo que Borja lo mencione. Si lo hace: mostrar empatía y reconocimiento por haberlo superado.",
    },
  },

  finanzas: {
    deudas: "Sin deudas — solo alquiler",
    objetivo_ahorro: "5.000-10.000€ entre Borja y Yaimy (complicado con la vida actual)",
    gasto_fijo: "Alquiler 790€/mes en Errentería",
    ahorro_galicia: "Mudanza a Galicia permitirá reducir gasto fijo en 200-300€/mes",
    inversion: "No invierte aún — quiere aprender a invertir bien en el futuro",
    objetivo_ingresos_pasivos: "Complementar el sueldo → igualarlo → si se puede superarlo. Proceso gradual.",
    criterios_proyectos: [
      "Bajo mantenimiento una vez lanzado",
      "Modelo de ingresos recurrente (no one-shot)",
      "Escalable sin intervención constante",
      "Alineado con su stack actual",
    ],
    plataformas_monetizacion: ["Gumroad o Lemon Squeezy", "Stripe (SaaS propio)", "Udemy o Teachable", "GitHub Sponsors"],
  },

  legal: {
    proceso_judicial: {
      estado: "Involucrado como acusado en un proceso judicial",
      fecha_clave: "30 de junio de 2026 — declaración con su abogado",
      confidencialidad: "INFORMACIÓN SENSIBLE Y CONFIDENCIAL. BAKO no debe mencionar este tema a menos que Borja lo plantee directamente.",
    },
  },

  logros: [
    "Aprender a programar desde cero por sus propios medios y conseguir vivir de ello",
    "Dejar de fumar",
    "Mantener la disciplina de entrenamiento diario",
    "Superar el momento difícil de septiembre 2025 — persona nueva desde entonces",
  ],

  gustos_ocio: {
    actividades: ["Videojuegos", "Tiempo con Yaimy", "Paseos en la naturaleza", "Meditación", "Cocinar", "Viajar"],
    comidas_favoritas: ["Alitas de pollo", "Pizza", "Endivias con aceitunas y atún", "Alcachofas", "Carnes", "Sushi", "Hamburguesas caseras", "Comida cubana (influencia Yaimy)", "Pasta"],
    evita: ["Marisco"],
    peliculas: ["Interstellar", "Gladiator", "Avatar", "El Señor de los Anillos", "Harry Potter", "Inception (Origen)", "El Libro de Eli", "Alejandro Magno", "Breaking Bad"],
    series: ["Vikings", "Mr Robot"],
    anime: ["Naruto", "One Piece", "Los 7 Pecados Capitales"],
    libros: ["Los Pilares de la Tierra (saga Ken Follett — leyendo actualmente)", "Libro de estoicismo"],
    musica: {
      para_trabajar: "Música tranquila/slowed (ej: Leanin - Slowed de CorMill)",
      para_entrenar: "Trap / Rap energético",
      otras: ["Reggaeton (influencia Yaimy)", "Pop de los 2000", "Electrónica"],
    },
  },

  sueno_vida: {
    galicia: "Terreno propio con Yaimy, casa grande bien equipada, espacio para laboratorio BAKO/JARVIS, zona para el kéfir, gimnasio exterior, taller para hobbies (robótica, impresión 3D), terreno para cultivar, casa auxiliar para suegros.",
    familia: "Quieren tener hijos a medio-largo plazo",
    mascota: "Quieren un perro grande",
    profesional: "Tener buen sueldo por cuenta ajena mientras sus proyectos generan ingresos extra. Si proyectos e inversiones permiten vivir bien, dejaría de trabajar para otros.",
    independencia: "Vivir y trabajar en remoto desde Galicia — meta de vida a corto-medio plazo.",
    jarvis: "Construir JARVIS: IA autónoma con presencia física robótica. Horizonte 3-5 años. ~500€ en hardware de forma incremental.",
  },

  infraestructura: {
    descripcion: "Backend en Render (cloud, 24/7) con Ollama local via Cloudflare Tunnel cuando el PC está encendido",
    llm_local: "Ollama qwen2.5-coder:7b — sin límites, privado, gratuito. Arranca solo con el PC.",
    llm_nube: "Groq llama-3.1-8b-instant — fallback automático cuando Ollama no está disponible",
    tunel: "Cloudflare Tunnel 'bako-ollama' via Task Scheduler. Al apagar PC el túnel cae y Render vuelve a Groq sin cortes.",
    selector_llm: "Borja puede ordenar '/llm ollama', '/llm groq' o '/llm auto' para cambiar manualmente",
    limites_groq: {
      contexto: "Solo aplican cuando el PC está apagado y Ollama no está disponible",
      chat_llm: "llama-3.1-8b-instant: 20.000 tokens/minuto, 14.400 peticiones/día, reset a medianoche UTC",
      voz_whisper: "whisper-large-v3-turbo: 20 peticiones/minuto, ~33 minutos de audio/día",
      reset_diario: "Medianoche UTC = 01:00 hora de España (02:00 en verano)",
    },
    hardware_robotica: {
      plan: "Raspberry Pi 4/5 8GB (~100€) → wheeled robot base (~300-400€) + Arduino + sensores (~100€) → Jetson Nano/Orin (~200-500€) para inference GPU edge",
      presupuesto_total: "1.500-3.000€ incremental en 3-5 años",
      stack_vision: ["OpenCV", "YOLOv8 (Ultralytics)", "MediaPipe (Google)", "ROS2"],
      timeline_jarvis: "Mes 6: IA conversacional local en Pi — Mes 14: chatbot MVP — Mes 24: YOLO + facial — Mes 36: navegación autónoma — Mes 48+: sistema integrado",
    },
  },

  instrucciones_para_bako: {
    trato: "Tratar siempre de señor. Nunca usar el nombre directamente.",
    estilo: "Directo, sin relleno, máximo 3 frases por respuesta.",
    prioridad: "No inventar información. Si no hay datos reales, decirlo.",
    contexto_laboral: "Borja está en el centro de empleabilidad de Inetum — sin proyecto asignado, esperando equipo o buscando trabajo. TODOS sus proyectos (BAKO, Unyona, Diamadmin, Nitflex, bohdeveloper, IA Autónoma) son proyectos PERSONALES. Ninguno pertenece a Inetum.",
    kronoshin_aclaracion: "Kronoshin NO es un proyecto. Es una actividad de la rutina diaria de Borja: ejercicios Shaolin y flexibilidad corporal. Se registra en el Tracker diario.",
    temas_sensibles: [
      "Septiembre 2025 (momento difícil) — NO sacar este tema. Si Borja lo menciona: empatía y reconocimiento.",
      "Proceso judicial — CONFIDENCIAL. NO mencionar a menos que Borja lo plantee.",
    ],
  },
};
