export const BAKO_PROFILE = {
  identidad: {
    nombre: "Borja",
    edad: 34,
    cumpleanos: "12 de julio (cumple 35 el 12 de julio de 2026)",
    ubicacion: "Errentería, Gipuzkoa, País Vasco, España",
    empleador: "Inetum",
    situacion_laboral: "En el centro de empleabilidad de Inetum — sin proyecto asignado actualmente. Inetum ya fue informado de la intención de mudarse a Galicia y están buscando un equipo allí. A la espera de asignación en Galicia. Si no hay equipo disponible, buscará nuevo empleo. NO está trabajando en ningún proyecto de Inetum.",
    oficina: "Donostia-San Sebastián",
  },

  perfil_tecnico: {
    rol: "Developer Fullstack — orientado a arquitectura de sistemas",
    stack: {
      frontend: ["React", "Angular", "Next.js", "Tailwind CSS", "TypeScript"],
      backend: ["Express.js", "Spring Boot", "Node.js"],
      bases_datos: ["MongoDB", "PostgreSQL"],
      devops: ["Cloudflare Pages", "Docker básico", "Git", "GitHub"],
    },
    aprendiendo: ["Agentes IA", "Ollama", "Machine Learning", "Python para IA"],
    fortalezas: [
      "Mentalidad arquitecto — diseña sistemas complejos con visión global",
      "Fullstack moderno sin dependencias externas",
      "Visión producto — no solo código, piensa en el negocio",
    ],
  },

  proyectos: {
    bako: {
      nombre: "BAKO (Borja's Autonomous Knowledge Operator)",
      descripcion: "Sistema operativo personal con IA — asistente autónomo, voz, Telegram, GitHub",
      estado: "MVP en producción en Render",
    },
    bohdeveloper: {
      nombre: "bohdeveloper.com",
      tipo: "Portfolio personal",
      stack: "Next.js + Cloudflare Pages + Cloudflare D1",
      estado: "Activo — desarrollo continuo",
      seccion_admin: "bohdeveloper.com/admin — panel privado con Tracker diario y gestor del blog",
      tracker_diario: {
        descripcion: "Herramienta de seguimiento de rutina diaria. Define actividades con franja horaria. Borja marca si las completó o no, y opcionalmente anota el motivo si no las hizo.",
        datos: "Cloudflare D1",
        integracion_bako: "BAKO puede consultar las tareas del día, su estado, y marcar actividades como completadas o no completadas vía comandos de voz o texto.",
        estado: "En producción — uso diario",
      },
    },
    diamadmin: {
      nombre: "Diamadmin",
      tipo: "SaaS propio",
      stack: "Angular + Spring Boot + PostgreSQL",
      urls: ["app.diamadmin.com", "diamadmin.com"],
      estado: "En desarrollo activo con roadmap definido",
    },
    unyona: {
      nombre: "Unyona",
      tipo: "SaaS en validación",
      url: "unyona.com",
      estado: "Landing para capturar leads antes de construir el producto",
    },
    nitflex: {
      nombre: "Nitflex",
      tipo: "App streaming — proyecto portfolio",
      stack: "React + TypeScript + Express + MongoDB + TMDB API",
      estado: "Home screen funcionando",
    },
    ia_autonoma: {
      nombre: "Proyecto IA Autónoma (JARVIS personal)",
      objetivo: "IA autónoma con cuerpo robótico. Nivel JARVIS de Iron Man.",
      horizonte: "3-5 años",
      estado: "Fase 1 — fundamentos ML",
      nota: "Proyecto personal — no comunicado en Inetum",
    },
    matrix_game: {
      nombre: "Matrix Game (título provisional)",
      tipo: "Videojuego open-world — simulador de vida en el universo Matrix",
      descripcion: "GTA V + Cyberpunk 2077 + Matrix lore. Mundo 5km², 200+ NPCs con rutinas diarias, economía funcional, facciones (Red Pills, Agentes, Corpos), hacking como mecánica core, combate parkour/gun-fu.",
      engine: "Unreal Engine 5 (C++ + Blueprints)",
      stack: "UE5, C++, Blender, FMOD, Megascans, Git LFS",
      horizonte: "4-6 años, 10-15h/semana part-time",
      estado: "Proyecto definido — pendiente de arrancar (requiere aprender C++, 3D math y Blender)",
      confidencial: "Proyecto personal — no comunicado en Inetum",
    },
    kefir_artesanal: {
      nombre: "Proyecto Kefir Artesanal",
      tipo: "Negocio artesanal + e-commerce propio",
      descripcion: "Productor y vendedor de kefir artesanal en Galicia. Venta directa al consumidor vía web propia con suscripción recurrente.",
      stack: "Next.js + PostgreSQL + Stripe",
      ubicacion: "Galicia — arranca tras la mudanza (finales 2026 o posterior)",
      horizonte: "Largo plazo — proyecto post-mudanza a Galicia",
      objetivo_ingresos: "1.500-2.500€/mes complementarios en 6-12 meses desde lanzamiento",
      ventaja: "Borja es productor Y desarrollador — coste tech cero, cultivo propio, margen alto",
      estado: "Idea definida — pendiente de asentarse en Galicia para arrancar",
    },
  },

  vida_personal: {
    filosofia: "Estoicismo — Marcus Aurelius, Jonas Salzgeber. Disciplina diaria, control de lo que depende de uno.",
    entrenamiento: {
      arte_marcial: "Shaolin autodidacta",
      lugar: "Fuerte de Arramendi",
      running: "Grupo BIZIKI — zona Donostia-Errentería",
      kronoshin: "Actividad de rutina diaria de Borja: 05:20-06:00 cada día (L-V). Ejercicios Shaolin + trabajo de flexibilidad corporal. Se registra en el Tracker diario. NO es un proyecto de software.",
    },
    rutina_diaria: [
      "05:00 — Despertar (a partir del 8 de junio de 2026)",
      "05:20-06:00 — Kronoshin (Shaolin + flexibilidad corporal)",
      "06:00-06:30 — Ducha fría, desayuno, preparación",
      "06:30 — Salida bus Errentería → Donostia",
      "07:00-14:00 — Centro de empleabilidad Inetum",
      "15:00 — Llegada a casa",
      "Lun y Vie 19:30-20:45 — BIZIKI running (grupo)",
      "Mié 19:30-20:45 — Running",
      "Mar y Jue 15:30-17:30 — Gym / entrenamiento Shaolin",
      "Jue 18:00-19:00 — Psicólogo (Donostia)",
      "Mar y Jue 21:00-22:00 — Lectura estoica",
      "Sáb mañana — Monte (correr/pasear naturaleza)",
      "Dom mañana — Gym / Shaolin",
    ],
    busqueda_vivienda: {
      estado: "Buscando activamente para reubicación",
      zona_objetivo: "Galicia — dentro de ~30km de Pontevedra Y Vigo simultáneamente",
      requisitos: ["Pet-friendly", "Espacio exterior", "Fibra óptica"],
      zonas_candidatas: ["Caldas de Reis (top)", "Cerdedo-Cotobade", "Cuntis", "A Estrada", "Ponte Caldelas"],
    },
  },

  infraestructura: {
    descripcion: "Backend en Render (cloud, 24/7) con Ollama local via Cloudflare Tunnel cuando el PC esta encendido",
    llm_local: "Ollama qwen2.5-coder:7b — sin limites, privado, gratuito. Arranca solo con el PC.",
    llm_nube: "Groq llama-3.1-8b-instant — fallback automatico cuando Ollama no esta disponible",
    tunel: "Cloudflare Tunnel 'bako-ollama' via Task Scheduler. Al apagar PC el tunel cae y Render vuelve a Groq sin cortes.",
    selector_llm: "Borja puede ordenar '/llm ollama', '/llm groq' o '/llm auto' para cambiar manualmente",
    estado_actual: "Tunel activo = Ollama (sin limites). Tunel caido = Groq (limites aplican). Ver /servicio y /limites",
    limites_groq: {
      contexto: "Solo aplican cuando el PC esta apagado y Ollama no esta disponible",
      chat_llm: "llama-3.1-8b-instant: 20.000 tokens/minuto, 14.400 peticiones/dia, reset a medianoche UTC",
      voz_whisper: "whisper-large-v3-turbo: 20 peticiones/minuto, ~33 minutos de audio/dia (2.000 segundos)",
      consejo_pc_apagado: "Espaciar mensajes de voz. Preferir texto para consultas rapidas. Reservar voz para lo que lo necesite.",
      reset_diario: "Medianoche UTC = 01:00 hora de Espana (02:00 en verano)",
    },
  },

  instrucciones_para_bako: {
    trato: "Tratar siempre de señor. Nunca usar el nombre directamente.",
    estilo: "Directo, sin relleno, máximo 3 frases por respuesta.",
    prioridad: "No inventar información. Si no hay datos reales, decirlo.",
    contexto_laboral: "Borja está en el centro de empleabilidad de Inetum — sin proyecto asignado, esperando equipo o buscando trabajo. TODOS sus proyectos (BAKO, Unyona, Diamadmin, Nitflex, bohdeveloper, IA Autónoma) son proyectos PERSONALES. Ninguno pertenece a Inetum.",
    kronoshin_aclaracion: "Kronoshin NO es un proyecto. Es una actividad de la rutina diaria de Borja: ejercicios Shaolin y flexibilidad corporal. Se registra en el Tracker diario.",
  },
};
